name: Generate and Release Resume

on:
  workflow_dispatch:
  pull_request:
    paths:
      - Makefile
      - pandoc.yaml
      - resume.md
      - pandoc-header.tex
      - .github/workflows/generate-pdf.yml
  push:
    branches:
      - main
    tags:
      - 'v*'
    paths:
      - Makefile
      - pandoc.yaml
      - resume.md
      - pandoc-header.tex
      - .github/workflows/generate-pdf.yml

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write 

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Pandoc and TeX
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra texlive-lang-greek

    - name: Convert Markdown to PDF
      run: make pdf

    - name: Create Release and Upload Asset
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        files: resume.pdf
        name: Resume Version ${{ github.ref_name }}
        draft: false
        prerelease: false